name: build

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      branch: main

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --locked

      - name: compress build
        run : gzip -f target/release/s3m

      - name: Upload binaries to release
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: s3m
          path: target/release/s3m.gz


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: s3m

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: s3m.gz
