---
name: Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    name: Build and release
    runs-on: ${{ matrix.os }}
    needs: test

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the release version from the tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: sudo apt -y install musl-dev musl-tools
        if: matrix.build == 'linux'

      - name: Install `cargo-generate-rpm`
        if: matrix.build == 'linux'
        run: cargo install cargo-generate-rpm

      - run: choco install openssl
        if: matrix.build == 'windows'

      - run: echo 'OPENSSL_DIR=C:\Program Files\OpenSSL-Win64' | Out-File -FilePath
          $env:GITHUB_ENV -Append
        if: matrix.build == 'windows'

      - name: Build Linux
        run: |
          cargo build --release --locked --target ${{ matrix.target }} --features "openssl/vendored"
        if: matrix.build == 'linux'

      - name: Generate RPM
        if: matrix.build == 'linux'
        run: |
          ls -alR target/${{ matrix.target }}/release/s3m
          mv target/${{ matrix.target }}/release/s3m ./target/release/s3m
          strip -s ./target/release/s3m
          cargo generate-rpm
          ls -alR target/generate-rpm  # Check where the RPM is generated
          RPM_PATH=$(find target/generate-rpm/ -name "*.rpm" -print -quit)
          echo "RPM_ASSET=$RPM_PATH" >> $GITHUB_ENV

      - name: Build
        run: |
          cargo build --release --locked --target ${{ matrix.target }}
        if: matrix.build != 'linux'

      - name: Build archive
        shell: bash
        run: |
          binary_name="s3m"

          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          else
            tar -czf "$dirname.tar.gz" "$dirname"
            echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
          fi

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |-
            ${{ env.ASSET }}
            ${{ env.RPM_ASSET }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  package:
    name: PackageCloud
    needs:
      - build
    uses: ./.github/workflows/packagecloud.yml
    secrets: inherit
